### PR TITLE
Clarify usage of pipe symbol in modparam

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by henningw** [comment]
Thanks for the PR. As you also included additional changes (besides the pipe extension), could you change the commit message to reflect that as well?

**Comment by dilyanpalauzov** [comment]
Please suggest a commit message.

**Comment by henningw** [comment]
> Please suggest a commit message.
I meant, the commit message should reflect the changes done in that commit. You are doing multiple changes (also some spelling fixes) in that commit, besides from the pipe extension. It would be better if you split the different changes into individual commits in the future.

If you can not change the commit message anymore, we can also merge it manually later on.

**Comment by dilyanpalauzov** [comment]
In my eyes changing the commit message in this concrete case does not solve real-world problems.

Please suggest spelling of the commit message, which you think is appropriate.

**Comment by henningw** [comment]
> In my eyes changing the commit message in this concrete case does not solve real-world problems.
> Please suggest spelling of the commit message, which you think is appropriate.

It solves the particular "real-world" problem that somebody else can find out in the future what actually was changed in a particular commit by reading the commit message, without actually looking to the (larger, in this case 36 files) change.

**Comment by miconda** [comment]
Thanks for your efforts to improve content of the documentation, really appreciated!

I am going to apply this PR manually, splitting in a few commits and changing the modparam section to reflect better what the code is doing.

**Pull request closed without merging**
