### PR TITLE
Clarifications wait_worker1_usleep

### PR DESCRIPTION
**Pull request by dilyanpalauzov**

### CODE REVIEW

**Comment by miconda** [comment]
The new paragraph no longer mention that it waits to complete the `initialization`, which can be misleading to wait to complete everything.

The PR does also many other changes, the commit message should also reflect that. A commit message can have more than one line. The first line it is considered the subject of the message, then can be an empty line followed by many text lines describing the changes. So this PR can be eventually merged manually with updated content and commit message.

**Comment by dilyanpalauzov** [comment]
Please propose a wording for the commit message.

**Comment by miconda** [comment]
Maybe I haven't spotted all the changes, but a commit message can look like:

```
core cookbook: wait_worker1_usleep details, formatting and spell updates

- clarifications for wait_worker1_usleep
- removed < > around some socket value examples
```

**Comment by dilyanpalauzov** [comment]
> The new paragraph no longer mention that it waits to complete the `initialization`, which can be misleading to wait to complete everything.

I have updated the text to include the word initialization.  I am open to any other rewording of the sentence, as long as the suggestions contain complete sentences.

**Pull request merged**
