### PR TITLE
cmake: Update documenation

### PR DESCRIPTION
**Pull request by xkaraman**
I have split the docs into separate steps for configuration and building and change the table structure to have the comparison between `Makefiles` and `CMakeFiles` side by side. 

What are your thoughts about this documentation update?

### CODE REVIEW

**Comment by henningw** [comment]
Thank you. I would not add the jinja option to the comparison table, it might be confusing for new users. Maybe better creating a new page for usage with ninja build system.

**Comment by miconda** [comment]
Initial version of the file was with a table having side-by-side commands (https://github.com/kamailio/kamailio-wiki/blob/db4faaab7c9564880d32f0ff5eab659f1c90cc5b/docs/tutorials/cmake/commands.md), but I changed to one-after-the-other because for long description and long commands, the readability was not that good. Also copy&paste was not easy to do, lines being wrapped.

I am fine to split between config commands and build commands, but I would prefer the existing format rather than one row side-by-side.

**Comment by miconda** [comment]
And I also think that commands for ninja should be a separate page dedicated to it.

**Comment by xkaraman** [comment]
This PR was merged by mistake while pushing another commit.  
362b17ff42216ce6c66957dde8f64764ba696356 was reverted at 8773175073d287ea49176cf976d3d6c76b300e64

**Pull request merged**
